server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Skicka alla routes till index.html så React Router fungerar
    location / {
        try_files $uri $uri/ /index.html;
    }
}
